### ISSUE TITLE
Bug on mac terminal

### ISSUE THREAD

**Issue by mzhrisec** [720922/bountymeter#1]
Hi

work good as linux terminal but have problem in mac terminal 

<img width="1022" alt="Screenshot 2023-04-16 at 2 34 15 PM" src="https://user-images.githubusercontent.com/36299062/232304752-021f1656-ac3e-40b6-a39b-ca7ae454f53f.png">

**Comment by rynosec** [comment]
Hey @mzhrisec ,
Thanks for the issue, I am not familiar with mac environment tbh. I need to look into this, the best I can do right now is to write the tool in python from scratch and that should work fine :)

**Comment by rynosec** [comment]
I think mac by default uses zsh, in the meantime you can try switching to bash.

**Comment by rynosec** [comment]
For MacOS run 'brew install bash' and rerun installer in a new terminal

**Comment by mzhrisec** [comment]
Hi @720922 
Thanks for response 
Same error with bash terminal in mac but work fine in bash & zsh in linux 
<img width="1037" alt="Screenshot 2023-04-17 at 8 07 13 PM" src="https://user-images.githubusercontent.com/36299062/232590958-fbe8bf8d-2f04-4361-8e23-f46432d92b8b.png">

**Comment by rynosec** [comment]
Hey @mzhrisec ,
I have completely rewritten the tool in python with custom logic, so you might wanna try that out and let me know :)
https://github.com/720922/bountymeterPY

Thanks,

**Comment by mzhrisec** [comment]
Hi @720922 
Thank you for rewritten with python, now it's work on my mac 
Thanks!!!
